### ISSUE TITLE
[Cloudy.Protobuf] The wire type could not be skipped, because there is no appropriate method

### ISSUE THREAD

**Issue by eigenein** [eigenein/cloudy#45]
```
System.Collections.Generic.KeyNotFoundException: The wire type could not be skipped, because there is no appropriate method: 4
   at Cloudy.Protobuf.Helpers.UnknownFieldSkipHelper.Skip(Stream stream, WireType wireType) in E:\Development\CSharp\nebulous\Cloudy\Cloudy.Protobuf\Helpers\UnknownFieldSkipHelper.cs:line 31
   at Cloudy.Protobuf.Serializer.Deserialize(Stream stream) in E:\Development\CSharp\nebulous\Cloudy\Cloudy.Protobuf\Serializer.cs:line 263
   --- End of inner exception stack trace ---
   at Cloudy.Protobuf.Serializer.Deserialize(Stream stream) in E:\Development\CSharp\nebulous\Cloudy\Cloudy.Protobuf\Serializer.cs:line 280
   at Cloudy.Protobuf.Interfaces.AbstractSerializer.Deserialize(Byte[] bytes) in E:\Development\CSharp\nebulous\Cloudy\Cloudy.Protobuf\Interfaces\AbstractSerializer.cs:line 36
   at Cloudy.Messaging.Structures.ByteArrayValue.Get(Type type) in E:\Development\CSharp\nebulous\Cloudy\Cloudy\Messaging\Structures\ByteArrayValue.cs:line 28
   at Cloudy.Messaging.Structures.ByteArrayValue.Get[T]() in E:\Development\CSharp\nebulous\Cloudy\Cloudy\Messaging\Structures\ByteArrayValue.cs:line 19
   at Cloudy.Computing.Nodes.AbstractNode.ReceiveFrom[T](IPEndPoint endPoint) in E:\Development\CSharp\nebulous\Cloudy\Cloudy\Computing\Nodes\AbstractNode.cs:line 106
   at Cloudy.Computing.Nodes.AbstractSlaveNode`1.Cloudy.Computing.Interfaces.IEnvironmentTransport.ReceiveFromMaster[TMessage]() in E:\Development\CSharp\nebulous\Cloudy\Cloudy\Computing\Nodes\AbstractSlaveNode.cs:line 356
   at Cloudy.Computing.Environment.TryGetRemoteValue[TValue](Byte[] namespace, String key, TValue& value) in E:\Development\CSharp\nebulous\Cloudy\Cloudy\Computing\Environment.cs:line 118
   at Cloudy.Computing.Topologies.Helpers.StarTopologyHelper.GetThreadsCount(IEnvironment environment) in E:\Development\CSharp\nebulous\Cloudy\Cloudy\Computing\Topologies\Helpers\StarTopologyHelper.cs:line 25
   at Cloudy.Examples.Static.Pi.Slave.SlaveNode.Run(IEnvironment environment) in E:\Development\CSharp\nebulous\Cloudy\Cloudy.Examples.Static.Pi.Slave\SlaveNode.cs:line 63
```

**Comment by eigenein** [comment]
Либа тестирована Unit-тестами, так что скорее всего, перепутываются сообщения при передаче: ожидается одно, а приходит другое.

**Comment by eigenein** [comment]
#56 - более актуален после добавления проверки тега.
