### ISSUE TITLE
IndexOutOfRangeException

### ISSUE THREAD

**Issue by eigenein** [eigenein/cloudy#46]
```
22:16:06.9928 Error: System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at System.Collections.Generic.Dictionary`2.Resize()
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at Cloudy.Messaging.MessageDispatcher`1.BeginSend[T](TEndPoint endPoint, T message, Int32 tag, AsyncCallback callback, Object state) in E:\Development\CSharp\nebulous\Cloudy\Cloudy\Messaging\MessageDispatcher.cs:line 135
   at Cloudy.Messaging.MessageDispatcher`1.Send[T](TEndPoint endPoint, T message, Int32 tag, TimeSpan timeout) in E:\Development\CSharp\nebulous\Cloudy\Cloudy\Messaging\MessageDispatcher.cs:line 193
   at Cloudy.Computing.Nodes.AbstractNode.Send[T](IPEndPoint endPoint, T message, Int32 tag) in E:\Development\CSharp\nebulous\Cloudy\Cloudy\Computing\Nodes\AbstractNode.cs:line 92
   at Cloudy.Computing.Nodes.AbstractMasterNode.StopThread(IPEndPoint targetEndPoint, ThreadContext thread) in E:\Development\CSharp\nebulous\Cloudy\Cloudy\Computing\Nodes\AbstractMasterNode.cs:line 493
   at Cloudy.Computing.Nodes.AbstractMasterNode.<>c__DisplayClass18.<StopAllThreads>b__17(Object o) in E:\Development\CSharp\nebulous\Cloudy\Cloudy\Computing\Nodes\AbstractMasterNode.cs:line 476
```

**Comment by eigenein** [comment]
А как такое вообще возможно о0? [Здесь](http://msdn.microsoft.com/en-us/library/k7z0zy8k.aspx) вообще ничего нет про `IndexOutOfRangeException`.
