### ISSUE TITLE
The thread was not found in the network

### ISSUE THREAD

**Issue by eigenein** [eigenein/cloudy#54]
### Reproducing

Run the master, then 2 slaves each of 2 threads **without debugger**.
### Result

```
Error: Unhandled Exception: System.Collections.Generic.KeyNotFoundException: The thread was not found in the network: 08-04
   at Cloudy.Computing.Nodes.AbstractSlaveNode`1.ResolveThreadToEndPoint(Byte[] destination) in C:\Users\eigenein\My Projects\Personal\Cloudy\Cloudy\Computing\Nodes\AbstractSlaveNode.cs:line 435
   at Cloudy.Computing.Nodes.AbstractSlaveNode`1.SendEnvironmentOperation(Byte[] recipient, EnvironmentOperationValue operationValue) in C:\Users\eigenein\My Projects\Personal\Cloudy\Cloudy\Computing\Nodes\AbstractSlaveNode.cs:line 547
   at Cloudy.Computing.Nodes.AbstractSlaveNode`1.SendEnvironmentOperation(EnvironmentOperationValue operationValue) in C:\Users\eigenein\My Projects\Personal\Cloudy\Cloudy\Computing\Nodes\AbstractSlaveNode.cs:line 408
   at Cloudy.Computing.Nodes.AbstractSlaveNode`1.Cloudy.Computing.Interfaces.IEnvironmentTransport.Send(EnvironmentOperationValue operationValue) in C:\Users\eigenein\My Projects\Personal\Cloudy\Cloudy\Computing\Nodes\AbstractSlaveNode.cs:line 361
   at Cloudy.Computing.Environment`1.Reduce[T](Int32 tag, ReduceOperation operation, IEnumerable`1 targets) in C:\Users\eigenein\My Projects\Personal\Cloudy\Cloudy\Computing\Environment.cs:line 271
   at Cloudy.Computing.Environment`1.Reduce[T](Int32 tag, T value, ReduceOperation operation, IEnumerable`1 targets) in C:\Users\eigenein\My Projects\Personal\Cloudy\Cloudy\Computing\Environment.cs:line 292
   at Cloudy.Examples.Static.Pi.Slave.SlaveNode.Run(IEnvironment environment) in C:\Users\eigenein\My Projects\Personal\Cloudy\Cloudy.Examples.Static.Pi.Slave\SlaveNode.cs:line 79
   at Cloudy.Computing.ComputingThread.Run(IEnvironment environment) in C:\Users\eigenein\My Projects\Personal\Cloudy\Cloudy\Computing\ComputingThread.cs:line 23
   at Cloudy.Computing.ComputingThreadWrapper.Run(Object state) in C:\Users\eigenein\My Projects\Personal\Cloudy\Cloudy\Computing\ComputingThreadWrapper.cs:line 74
```

**Comment by eigenein** [comment]
```
00.1209 : Starting Slave ...
00.1429 : Joining the network at 127.0.0.1:2011 ...
00.1799 : Out: 0A-0D-0A-09-08-B8-1F-12-04-7F-00-00-01-10-06-10-05-18-02
00.1949 : In:  10-01-18-02
00.2099 : In:  0A-1F-0A-09-08-B8-1F-12-04-7F-00-00-01-12-10-61-16-10-3A-84-7F-77-4B-95-F1-F6-86-19-BE-FB-53-18-04-10-07-18-02
00.2099 : Out: 10-01-18-02
00.2229 : State: Joined
00.2229 : Joined: 127.0.0.1:2012 -> 3a101661-7f84-4b77-95f1-f68619befb53
00.2229 : Press Enter to quit.
07.5274 : In:  0A-04-0A-02-08-00-10-0B-18-06
07.5274 : Out: 10-01-18-06
07.5374 : In:  0A-04-0A-02-08-02-10-0B-18-08
07.5374 : Out: 10-01-18-08
07.5564 : In:  0A-04-0A-02-08-04-10-0B-18-0A
07.5564 : Out: 10-01-18-0A
07.5564 : Running
07.5564 : Thread Started: 08-00
07.5844 : In:  10-01-18-04
07.5844 : Out: 0A-19-0A-00-12-15-54-6F-70-6F-6C-6F-67-79-2E-54-68-72-65-61-64-73-43-6F-75-6E-74-10-29-18-04
07.6164 : Running
07.6334 : Thread Started: 08-02
07.6334 : Running
07.6334 : Thread Started: 08-04
08.6904 : In:  0A-06-18-02-0A-02-08-0C-10-2B-18-12
08.6904 : Out: 10-01-18-12
10.5975 : Out: 0A-19-0A-00-12-15-54-6F-70-6F-6C-6F-67-79-2E-54-68-72-65-61-64-73-43-6F-75-6E-74-10-29-18-06
10.5975 : In:  10-01-18-06
10.6095 : In:  0A-06-18-02-0A-02-08-0C-10-2B-18-1A
10.6095 : Threads Count: 6. Rank: 0.
10.6095 : Out: 0A-19-0A-00-12-15-54-6F-70-6F-6C-6F-67-79-2E-54-68-72-65-61-64-73-43-6F-75-6E-74-10-29-18-08
10.6095 : Part of Pi: 0.525099235702481
10.6295 : Out: 10-01-18-1A
10.6295 : In:  10-01-18-08
10.6465 : In:  0A-06-18-02-0A-02-08-0C-10-2B-18-1C
10.6465 : Out: 10-01-18-1C
10.6465 : Threads Count: 6. Rank: 1.
10.6715 : Part of Pi: 0.524765902605267
10.6715 : In:  10-01-18-0A
10.6715 : Out: 0A-19-0A-00-12-15-54-6F-70-6F-6C-6F-67-79-2E-54-68-72-65-61-64-73-43-6F-75-6E-74-10-29-18-0A
10.7355 : Out: 0A-04-0A-02-08-02-10-0F-18-0C
10.7225 : In:  0A-06-18-02-0A-02-08-0C-10-2B-18-1E
10.7515 : Out: 10-01-18-1E
10.7515 : In:  10-01-18-0C
10.7825 : Thread Stopped: 08-02
13.7367 : Out: 0A-19-0A-00-12-15-54-6F-70-6F-6C-6F-67-79-2E-54-68-72-65-61-64-73-43-6F-75-6E-74-10-29-18-0E
13.7367 : In:  10-01-18-0E
13.7497 : In:  0A-06-18-02-0A-02-08-0C-10-2B-18-20
13.7497 : Out: 0A-04-0A-02-08-06-10-1D-18-10
13.7497 : Threads Count: 6. Rank: 2.
13.7607 : Part of Pi: 0.524432234341364
13.7607 : Out: 10-01-18-20
13.7607 : In:  10-01-18-10
13.8037 : In:  0A-18-0A-09-08-BA-1F-12-04-7F-00-00-01-12-09-08-BA-1F-12-04-7F-00-00-01-18-01-10-1F-18-22
13.8057 : Out: 0A-04-0A-02-08-06-10-1D-18-12
13.8057 : Out: 0A-04-0A-02-08-00-10-11-18-14
13.8247 : Out: 10-01-18-22
13.8247 : In:  10-01-18-12
13.8247 : In:  10-01-18-14
13.8377 : Out: 0A-04-0A-02-08-04-10-11-18-16
13.8377 : In:  0A-18-0A-09-08-BA-1F-12-04-7F-00-00-01-12-09-08-BA-1F-12-04-7F-00-00-01-18-01-10-1F-18-24
13.8547 : Out: 10-01-18-24
13.9227 : Thread Stopped: 08-00
13.9227 : In:  10-01-18-16
```

**Comment by eigenein** [comment]
Вроде пофиксил.
